--disable-xinput2 (and enable) added

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -31,6 +31,7 @@ LIBS="$LIBS $X_LIBS"
 AC_CHECK_LIB(c, dlopen, LIBDL="", [AC_CHECK_LIB(dl, dlopen, LIBDL="")])
 AC_CHECK_LIB(c, sem_init, LIBSEMA="CCC", [AC_CHECK_LIB(pthread, sem_init, LIBSEMA="-lpthread")])
 AC_CHECK_LIB(Xtst, XTestFakeMotionEvent, LIBXTST="-lXtst",[AC_CHECK_LIB(Xext,XTestFakeMotionEvent , LIBXTST="-lXext")])
+AC_CHECK_HEADERS(X11/extensions/XInput2.h, HAS_XI2="true",HAS_XI2="false",)
 
 GENERATION_DIRS=""
 
@@ -91,6 +92,14 @@ AC_ARG_ENABLE(doconly,
 	no)  doconly=false ;;
 	*) AC_MSG_ERROR(bad value ${enableval} for --disable-doconly) ;;
 	    esac],[doconly=false])
+
+AC_ARG_ENABLE(xinput2,
+    [  --enable-xinput2       build Xnee with support for XInput2],
+    [case "${enableval}" in
+	yes) use_xi2=true ;;
+	no)  use_xi2=false ;;
+	*) AC_MSG_ERROR(bad value ${enableval} for --disable-xinput2) ;;
+	    esac],[use_xi2=true])
 
 AC_ARG_ENABLE(cli,
     [  --enable-cli       build Xnee command line tool],
@@ -185,6 +194,7 @@ AM_CONDITIONAL(XOSD, test x$xosd = xtrue)
 AM_CONDITIONAL(DOCONLY, test x$doconly = xtrue)
 AM_CONDITIONAL(BUILD_STATIC, test x$makestatic = xtrue)
 AM_CONDITIONAL(NOT_INSTALL_LIBS, test x$buildlib = xfalse)
+AM_CONDITIONAL(XNEE_XINPUT_SUPPORT, test x$use_xi2 = xtrue)
 
 if test x$verbose = xtrue ;
 then
@@ -228,6 +238,14 @@ then
     PEDANTIC_FLAGS=
 else
     PEDANTIC_FLAGS=
+fi
+
+
+if test x$use_xi2 = xtrue;
+then
+    XNEE_XINPUT_SUPPORT_FLAGS=-DXNEE_XINPUT_SUPPORT
+else
+    XNEE_XINPUT_SUPPORT_FLAGS= 
 fi
 
 
@@ -475,6 +493,27 @@ else
 fi
 
 
+check_xinput2()
+{
+    if test x$use_xi2 = xtrue ;
+	then
+	if test x$HAS_XI2 = xfalse ;
+	    then
+	    echo "XInput2 not found"
+	    echo "To compile GNU Xnee you have to:"
+	    echo "  *  Install XInput2 (development package)"
+	    echo "or"
+	    echo "  *  Disable XInput2 support in GNU Xnee:"
+	    echo "         ./configure --disable-xinput2"
+	    echo " "
+	    exit 1
+	fi
+   fi
+}
+
+check_xinput2
+
+
 dnl if test x$builddoc = xtrue ; 
 dnl then
 dnl 	DOC_DIR=doc
@@ -516,6 +555,8 @@ show_doc_program()
 
 DOC_NOT_BUILT_WARNING=false
 MISSING_PROGRAMS=""
+
+
 
 
 
@@ -760,6 +801,7 @@ echo "    GCOV_FLAG            $GCOV_FLAG"
 echo "    GPROF_FLAG           $GPROF_FLAG"
 echo "    BUF_VERBOSE_FLAG     $BUF_VERBOSE_FLAG"
 echo "    PEDANTIC_FLAGS       $PEDANTIC_FLAGS"
+echo "    XNEE_XINPUT_SUPPORT_FLAGS $XNEE_XINPUT_SUPPORT_FLAGS"
 echo "    LIBDL                $LIBDL"
 echo "    LIBSEMA              $LIBSEMA"
 echo "    X11_LIBS             $X11_LIBS"
@@ -811,6 +853,15 @@ then
 else
     echo "        static"
 fi
+echo ""
+echo "   Support for XInput2"
+echo "   -------------------------------------"
+if test "x$XNEE_XINPUT_SUPPORT_FLAGS" = "x" ;
+then
+    echo "        disabled"
+else
+    echo "        enabled"
+fi
 echo " "
 echo "   Settings ok?"
 echo "   -------------------------------------"
@@ -827,3 +878,4 @@ echo "       make"
 echo "    and (perhaps as root)"
 echo "       make install"
 echo " "
+
