Searching for binaries, libs (X11). Warns if not finding prog needed by docs

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -15,10 +15,30 @@ AC_PATH_XTRA
 AC_FUNC_VPRINTF
 AC_CHECK_HEADERS(stdarg.h varargs.h, break)
 
-AC_CHECK_LIB(c, dlopen, LIBDL="", [AC_CHECK_LIB(dl, dlopen, LIBDL="-ldl")])
-AC_CHECK_LIB(c, sem_init, LIBSEMA="", [AC_CHECK_LIB(pthread, sem_init, LIBSEMA="-lpthread")])
+# Add X libs 
+LIBS="$LIBS $X_LIBS"
 
-X11_LIBS="-lX11 -lXtst"
+AC_CHECK_LIB(c, dlopen, LIBDL="", [AC_CHECK_LIB(dl, dlopen, LIBDL="")])
+AC_CHECK_LIB(c, sem_init, LIBSEMA="", [AC_CHECK_LIB(pthread, sem_init, LIBSEMA="")])
+AC_CHECK_LIB(Xtst, XTestFakeMotionEvent, LIBXTST="-lXtst",[AC_CHECK_LIB(Xext,XTestFakeMotionEvent , LIBXTST="-lXext")])
+
+
+if test "x$LIBXTST" = "x" ; 
+then
+    echo ""
+    echo " **** ERROR **** "
+    echo ""
+    echo "Could not locate the needed X11 extensions:"
+    echo ""
+    echo "   RECORD"
+    echo "   XTest"
+    echo ""
+    echo "Make sure you have them installed before building Xnee"
+    echo ""
+    echo "  ... on Debian do: apt-get install libxtst-dev"
+    echo " "
+    exit 1
+fi
 
 AC_ARG_ENABLE(gui,
 [  --enable-gui       build the GUI frontend to Xnee],
@@ -168,10 +188,13 @@ else
 fi
 
 
+
 dnl Forward some variables to the makefiles
 AC_SUBST(LIBDL)
 AC_SUBST(LIBSEMA)
+X11_LIBS="-lX11 $LIBXTST"
 AC_SUBST(X11_LIBS)
+
 
 AM_MAINTAINER_MODE
 AM_CONFIG_HEADER(config.h)
@@ -247,11 +270,84 @@ fi
 
 
 
+DOC_NOT_BUILT_WARNING=false
+check_program()
+{
+    PROG_VAR_TO_CHECK=$1
+    PROG_TO_CHECK=$2
+    COMMENT_ON_FAIL=$3
+    
+    if test "x$PROG_VAR_TO_CHECK" = "x" 
+	then
+	echo ""
+	echo " **** Warning **** "
+	echo " * "
+	echo " * Failed to to find $PROG_TO_CHECK"
+	echo " * "
+	echo "$COMMENT_ON_FAIL"
+	echo " * "
+	echo " ****************** "
+	echo " "
+	#exit 1
+	DOC_NOT_BUILT_WARNING=true
+    fi
+}
+
+check_doc_program()
+{
+    check_program "$1" "$2" " * Suggested solutions: 
+ *    1) Build Xnee without documentation,
+ *      ./configure --disable-doc
+ *
+ *   2) Install $2
+ *
+ *   3) If $2 is installed (and not found) make sure $2 is in the PATH variable"
+}
+
 DOC_TARGETS="info txt"
 if test x$builddoc = xtrue ; 
 then
-	dnl	gnee/po/Makefile.in 
-	DOC_TARGETS="images html info txt pdf ps"
+	AC_PATH_PROG(DIA,dia,,)
+	check_doc_program "$DIA" "dia"
+
+	AC_PATH_PROG(TEXI2HTML,texi2html,,)
+	check_doc_program "$TEXI2HTML" "texi2html"
+
+	AC_PATH_PROG(DVI2PS,dvi2ps,,)
+	check_doc_program "$DVI2PS" "dvi2ps"
+
+	AC_PATH_PROG(PS2PDF,ps2pdf,,)
+	check_doc_program "$PS2PDF" "ps2pdf"
+
+	AC_PATH_PROG(EPSTOPDF,epstopdf,,)
+	check_doc_program "$EPSTOPDF" "epstopdf"
+
+	AC_PATH_PROG(CONVERT,convert,,)
+	check_doc_program "$CONVERT" "convert"
+
+#	AC_PATH_PROG(DOXYGEN,doxygen,,)
+#	check_doc_program "$DOXYGEN" "doxygen"
+
+	AC_PATH_PROG(MAKEINFO,makeinfo,,)
+	check_doc_program "$MAKEINFO" "makeinfo"
+
+
+	if test x$DOC_NOT_BUILT_WARNING = xtrue ;
+	    then
+	    echo " "
+	    echo " "
+	    echo "          WARNING"
+	    echo " " 
+	    echo " ** Documents are not built ** "
+	    echo " "
+	    echo " "
+	    DOC_DIR=""
+	    DOC_TARGETS=""
+	    builddoc=false
+	    doconly=false
+	else
+	    DOC_TARGETS="images html info txt pdf ps"
+	fi
 fi
 
 AC_SUBST(DOC_TARGETS)
@@ -267,6 +363,8 @@ AC_OUTPUT([ Makefile ])
 
 if test x$doconly = xtrue || test x$builddoc = xtrue  ; 
 then
+    echo ldldldll ldk ljj
+    sleep 20
         AC_OUTPUT([ doc/Makefile ])
 fi
 
